name: 01 - GitHub Actions Environments Enhancements

on:
  push:
    branches:
      - "feature/**"
      - develop
      - main

jobs:
  build-job:
    name: Build & Publish Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/cwvj-flask-app:${{ github.sha }}
            ${{ vars.DOCKERHUB_USERNAME }}/cwvj-flask-app:latest

  deploy-dev-job:
    name: Deploy to Development
    if: github.ref_name == 'develop'
    needs: build-job
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Display Branch Information
        run: |
          echo "Branch : ${{ github.ref_name }}"

      - name: Display Environment Configuration
        run: |
          echo "Application URL : ${{ vars.APP_URL }}"
          echo "Debug Mode      : ${{ vars.DEBUG_MODE }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Container
        run: |
          docker run -d \
            -p 5000:5000 \
            --name cwvj-flask-container \
            ${{ vars.DOCKERHUB_USERNAME }}/cwvj-flask-app:${{ github.sha }}

      - name: Smoke Test Application
        run: |
          sleep 5
          curl --fail http://127.0.0.1:5000/
          curl --fail http://127.0.0.1:5000/health

      - name: Display Container Logs
        run: docker logs cwvj-flask-container

  deploy-prod-job:
    name: Deploy to Production
    if: github.ref_name == 'main'
    needs: build-job
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Display Branch Information
        run: |
          echo "Branch : ${{ github.ref_name }}"

      - name: Display Environment Configuration
        run: |
          echo "Application URL : ${{ vars.APP_URL }}"
          echo "Debug Mode      : ${{ vars.DEBUG_MODE }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Container
        run: |
          docker run -d \
            -p 5000:5000 \
            --name cwvj-flask-container \
            ${{ vars.DOCKERHUB_USERNAME }}/cwvj-flask-app:${{ github.sha }}

      - name: Smoke Test Application
        run: |
          sleep 5
          curl --fail http://127.0.0.1:5000/
          curl --fail http://127.0.0.1:5000/health

      - name: Display Container Logs
        run: docker logs cwvj-flask-container